export enum Actions {
  GET_ALL_PLACES_SUCCESS = 'GET_ALL_PLACES_FAIL',
  GET_ALL_PLACES_FAIL = 'GET_ALL_PLACES_FAIL',
  CREATE_PLACE_SUCCESS = 'CREATE_PLACE_SUCCESS',
  CREATE_PLACE_FAIL = 'CREATE_PLACE_FAIL',
}
