export enum Actions {
    GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS",
    GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL",
    SIGNUP_SUCCESS = "SIGNUP_SUCCESS",
    SIGNUP_FAIL = "SIGNUP_FAIL",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAIL = "LOGIN_FAIL",
}